## Preprocessing for Model Training

In [16]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

### Read data and drop/convert columns

In [17]:
df = pd.read_csv("../data/clean/stats_salaries.csv")
df

,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,TEAM_ABBREVIATION,TEAM_NAME,GAME_DATE_EST,SEASON_START,WON_GAME,INFLATION_ADJ_SALARY
0,1630162,Anthony Edwards,F,36:22,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,MIN,Minnesota Timberwolves,2022-03-12,2021,1,10245480
1,1630162,Anthony Edwards,F,34:27,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,MIN,Minnesota Timberwolves,2022-03-11,2021,0,10245480
2,1630162,Anthony Edwards,F,25:29,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,MIN,Minnesota Timberwolves,2022-03-09,2021,1,10245480
3,1630162,Anthony Edwards,F,32:22,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,MIN,Minnesota Timberwolves,2022-02-28,2021,1,10245480
4,1630162,Anthony Edwards,F,37:46,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,MIN,Minnesota Timberwolves,2022-02-25,2021,0,10245480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1628473,Yakuba Ouattara,NaN,3:09,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,BKN,Brooklyn Nets,2017-10-03,2017,1,85683
492308,201582,Alexis Ajinca,NaN,8:30,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,NOP,New Orleans Pelicans,2017-10-13,2017,0,5503462
492309,201582,Alexis Ajinca,NaN,11:49,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,NOP,New Orleans Pelicans,2017-10-06,2017,0,5503462
492310,1627818,Kaleb Tarczewski,NaN,20:55,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,OKC,Oklahoma City Thunder,2016-10-13,2016,0,84546
492311,1763,Ryan Bowen,NaN,7:54,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,OKC,Oklahoma City Thunder,2009-11-22,2009,0,264010

It doesn't look like we need the `PLAYER_NAME`, `TEAM_ABBREVIATION`, or `GAME_DATE_EST` for training, so we can drop that.

In [18]:
df = df.drop(columns=['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GAME_DATE_EST'])
df

,PLAYER_ID,START_POSITION,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,TEAM_NAME,SEASON_START,WON_GAME,INFLATION_ADJ_SALARY
0,1630162,F,36:22,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,Minnesota Timberwolves,2021,1,10245480
1,1630162,F,34:27,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,Minnesota Timberwolves,2021,0,10245480
2,1630162,F,25:29,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,Minnesota Timberwolves,2021,1,10245480
3,1630162,F,32:22,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,Minnesota Timberwolves,2021,1,10245480
4,1630162,F,37:46,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,Minnesota Timberwolves,2021,0,10245480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1628473,NaN,3:09,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,Brooklyn Nets,2017,1,85683
492308,201582,NaN,8:30,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,New Orleans Pelicans,2017,0,5503462
492309,201582,NaN,11:49,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,New Orleans Pelicans,2017,0,5503462
492310,1627818,NaN,20:55,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,Oklahoma City Thunder,2016,0,84546
492311,1763,NaN,7:54,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,Oklahoma City Thunder,2009,0,264010

We also convert minutes played to just seconds:

In [19]:
df['SECS_PLAYED'] = df['MIN'].apply(lambda x: int(x.split(':')[0]) * 60 + int(x.split(':')[1]))
df = df.drop(columns=['MIN'])
df

,PLAYER_ID,START_POSITION,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,TEAM_NAME,SEASON_START,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED
0,1630162,F,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,Minnesota Timberwolves,2021,1,10245480,2182
1,1630162,F,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,Minnesota Timberwolves,2021,0,10245480,2067
2,1630162,F,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,Minnesota Timberwolves,2021,1,10245480,1529
3,1630162,F,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,Minnesota Timberwolves,2021,1,10245480,1942
4,1630162,F,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,Minnesota Timberwolves,2021,0,10245480,2266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1628473,NaN,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,Brooklyn Nets,2017,1,85683,189
492308,201582,NaN,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,New Orleans Pelicans,2017,0,5503462,510
492309,201582,NaN,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,New Orleans Pelicans,2017,0,5503462,709
492310,1627818,NaN,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,Oklahoma City Thunder,2016,0,84546,1255
492311,1763,NaN,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,Oklahoma City Thunder,2009,0,264010,474

### Convert `START_POSITION` into dummy columns

We convert the `START_POSITION` column into dummy columns first, to indicate what position a player started in. This will also help get rid of all `NaN` values (players who didn't start will have a 0 in all dummy columns).

In [20]:
positions = pd.get_dummies(df['START_POSITION'])
df = pd.concat([df, positions], axis=1).drop(columns=['START_POSITION'])
df

,PLAYER_ID,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,TEAM_NAME,SEASON_START,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G
0,1630162,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,Minnesota Timberwolves,2021,1,10245480,2182,0,1,0
1,1630162,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,Minnesota Timberwolves,2021,0,10245480,2067,0,1,0
2,1630162,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,Minnesota Timberwolves,2021,1,10245480,1529,0,1,0
3,1630162,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,Minnesota Timberwolves,2021,1,10245480,1942,0,1,0
4,1630162,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,Minnesota Timberwolves,2021,0,10245480,2266,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1628473,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,Brooklyn Nets,2017,1,85683,189,0,0,0
492308,201582,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,New Orleans Pelicans,2017,0,5503462,510,0,0,0
492309,201582,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,New Orleans Pelicans,2017,0,5503462,709,0,0,0
492310,1627818,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,Oklahoma City Thunder,2016,0,84546,1255,0,0,0
492311,1763,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,Oklahoma City Thunder,2009,0,264010,474,0,0,0

### Create season average dataframe

We create a separate season average dataframe to predict only on those values. Since salary is season-based, it might make more sense to predict based on season averages, since each individual game doesn't necessarily reflect the salary a player gets (i.e., a player will have "ups" and "downs").

In [21]:
cols = df.columns.tolist()
cols.remove('PLAYER_ID')
cols.remove('SEASON_START')

aggregations = {col: 'mean' for col in cols if not 'PCT' in col}
# For team name, we don't want an average
aggregations['TEAM_NAME'] = pd.Series.mode
# For plus-minus, sum to know total contribution over course of season
aggregations['PLUS_MINUS'] = 'sum'
avg_df = df.groupby(['PLAYER_ID', 'SEASON_START']).agg(aggregations)

# For percentages, we want to get total made / total attempted
def get_pct_values(s_df):
    fg_pct = s_df['FGM'].sum() / s_df['FGA'].sum() if s_df['FGA'].sum() > 0 else 0
    fg3_pct = s_df['FG3M'].sum() / s_df['FG3A'].sum() if s_df['FG3A'].sum() > 0 else 0
    ft_pct = s_df['FTM'].sum() / s_df['FTA'].sum() if s_df['FTA'].sum() > 0 else 0
    return pd.Series({'FG_PCT': fg_pct, 'FG3_PCT': fg3_pct, 'FT_PCT': ft_pct})
pct_df = df.groupby(['PLAYER_ID', 'SEASON_START']).apply(get_pct_values)

avg_df = avg_df.join(pct_df)
df = df.drop(columns=['PLAYER_ID'])
avg_df = avg_df.reset_index().drop(columns=['PLAYER_ID'])
avg_df

,SEASON_START,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,TEAM_NAME,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G,FG_PCT,FG3_PCT,FT_PCT
0,2003,1.440000,3.840000,0.860000,2.440000,0.280000,0.320000,0.200000,1.280000,1.480000,0.520000,0.320000,0.100000,0.580000,0.860000,4.020000,-15.0,Houston Rockets,0.440000,3697550.0,846.440000,0.0,0.000000,0.000000,0.375000,0.352459,0.875000
1,2004,1.602740,3.794521,0.849315,2.013699,0.698630,0.863014,0.219178,0.986301,1.205479,0.739726,0.452055,0.027397,0.520548,0.958904,4.753425,33.0,Chicago Bulls,0.534247,3938661.0,742.356164,0.0,0.000000,0.150685,0.422383,0.421769,0.809524
2,2005,0.771429,1.914286,0.314286,1.085714,0.114286,0.200000,0.142857,0.657143,0.800000,0.400000,0.171429,0.057143,0.314286,0.600000,1.971429,11.0,Chicago Bulls,0.457143,4190683.0,439.200000,0.0,0.000000,0.028571,0.402985,0.289474,0.571429
3,2006,0.833333,2.166667,0.583333,1.500000,0.166667,0.166667,0.166667,0.583333,0.750000,0.333333,0.000000,0.083333,0.416667,0.500000,2.416667,-2.0,Phoenix Suns,0.833333,1577882.0,378.750000,0.0,0.000000,0.000000,0.384615,0.388889,1.000000
4,2007,0.705882,1.941176,0.647059,1.529412,0.235294,0.235294,0.058824,0.647059,0.705882,0.588235,0.000000,0.058824,0.352941,0.705882,2.294118,-33.0,Phoenix Suns,0.941176,1590374.0,403.294118,0.0,0.000000,0.000000,0.363636,0.423077,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8587,2021,4.727273,9.393939,0.757576,2.575758,1.818182,2.545455,1.621212,3.848485,5.469697,2.969697,0.939394,0.560606,1.803030,3.681818,12.030303,-379.0,Houston Rockets,0.257576,1517981.0,1606.424242,0.0,0.969697,0.000000,0.503226,0.294118,0.714286
8588,2020,1.028571,2.057143,0.257143,0.857143,0.428571,0.514286,0.514286,1.142857,1.657143,0.371429,0.342857,0.114286,0.342857,1.085714,2.742857,-35.0,Washington Wizards,0.400000,940530.0,484.200000,0.0,0.142857,0.000000,0.500000,0.300000,0.833333
8589,2021,1.176471,2.000000,0.294118,0.558824,0.764706,1.029412,0.617647,0.852941,1.470588,0.500000,0.117647,0.176471,0.323529,1.264706,3.411765,54.0,Washington Wizards,0.323529,1517981.0,506.352941,0.0,0.000000,0.000000,0.588235,0.526316,0.742857
8590,2020,1.961538,5.153846,1.243590,3.487179,1.243590,1.435897,0.371795,1.756410,2.128205,3.576923,1.230769,0.243590,1.192308,2.243590,6.410256,47.0,Denver Nuggets,0.628205,3350400.0,1341.000000,0.0,0.000000,0.358974,0.380597,0.356618,0.866071
8591,2021,1.666667,4.727273,0.909091,3.136364,1.000000,1.287879,0.348485,1.590909,1.939394,3.469697,1.030303,0.363636,1.060606,1.984848,5.242424,-239.0,Denver Nuggets,0.560606,3200000.0,1160.015152,0.0,0.000000,0.075758,0.352564,0.289855,0.776471

### `TEAM_ABBREVIATION` to dummy columns

We also convert the team abbreviation to dummy variables. We expect this could have an effect since different teams have different salary caps.

In [22]:
df_teams = pd.get_dummies(df['TEAM_NAME'])
df = pd.concat([df, df_teams], axis=1).drop(columns=['TEAM_NAME'])
df

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,SEASON_START,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G,Atlanta Hawks,Boston Celtics,Brooklyn Nets,Charlotte Hornets,Chicago Bulls,Cleveland Cavaliers,Dallas Mavericks,Denver Nuggets,Detroit Pistons,Golden State Warriors,Houston Rockets,Indiana Pacers,Los Angeles Clippers,Los Angeles Lakers,Memphis Grizzlies,Miami Heat,Milwaukee Bucks,Minnesota Timberwolves,New Orleans Pelicans,New York Knicks,Oklahoma City Thunder,Orlando Magic,Philadelphia 76ers,Phoenix Suns,Portland Trail Blazers,Sacramento Kings,San Antonio Spurs,Toronto Raptors,Utah Jazz,Washington Wizards
0,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,2021,1,10245480,2182,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,2021,0,10245480,2067,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,2021,1,10245480,1529,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,2021,1,10245480,1942,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,2021,0,10245480,2266,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,2017,1,85683,189,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
492308,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,2017,0,5503462,510,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
492309,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,2017,0,5503462,709,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
492310,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,2016,0,84546,1255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
492311,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,2009,0,264010,474,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [23]:
# If two modes for team name (due to equal # of games played on each team), use the first team
avg_df['TEAM_NAME'] = avg_df['TEAM_NAME'].apply(lambda x: x[0] if isinstance(x, np.ndarray) else x)
avg_df_teams = pd.get_dummies(avg_df['TEAM_NAME'])
avg_df = pd.concat([avg_df, avg_df_teams], axis=1).drop(columns=['TEAM_NAME'])
avg_df

,SEASON_START,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G,FG_PCT,FG3_PCT,FT_PCT,Atlanta Hawks,Boston Celtics,Brooklyn Nets,Charlotte Hornets,Chicago Bulls,Cleveland Cavaliers,Dallas Mavericks,Denver Nuggets,Detroit Pistons,Golden State Warriors,Houston Rockets,Indiana Pacers,Los Angeles Clippers,Los Angeles Lakers,Memphis Grizzlies,Miami Heat,Milwaukee Bucks,Minnesota Timberwolves,New Orleans Pelicans,New York Knicks,Oklahoma City Thunder,Orlando Magic,Philadelphia 76ers,Phoenix Suns,Portland Trail Blazers,Sacramento Kings,San Antonio Spurs,Toronto Raptors,Utah Jazz,Washington Wizards
0,2003,1.440000,3.840000,0.860000,2.440000,0.280000,0.320000,0.200000,1.280000,1.480000,0.520000,0.320000,0.100000,0.580000,0.860000,4.020000,-15.0,0.440000,3697550.0,846.440000,0.0,0.000000,0.000000,0.375000,0.352459,0.875000,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2004,1.602740,3.794521,0.849315,2.013699,0.698630,0.863014,0.219178,0.986301,1.205479,0.739726,0.452055,0.027397,0.520548,0.958904,4.753425,33.0,0.534247,3938661.0,742.356164,0.0,0.000000,0.150685,0.422383,0.421769,0.809524,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2005,0.771429,1.914286,0.314286,1.085714,0.114286,0.200000,0.142857,0.657143,0.800000,0.400000,0.171429,0.057143,0.314286,0.600000,1.971429,11.0,0.457143,4190683.0,439.200000,0.0,0.000000,0.028571,0.402985,0.289474,0.571429,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2006,0.833333,2.166667,0.583333,1.500000,0.166667,0.166667,0.166667,0.583333,0.750000,0.333333,0.000000,0.083333,0.416667,0.500000,2.416667,-2.0,0.833333,1577882.0,378.750000,0.0,0.000000,0.000000,0.384615,0.388889,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,2007,0.705882,1.941176,0.647059,1.529412,0.235294,0.235294,0.058824,0.647059,0.705882,0.588235,0.000000,0.058824,0.352941,0.705882,2.294118,-33.0,0.941176,1590374.0,403.294118,0.0,0.000000,0.000000,0.363636,0.423077,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8587,2021,4.727273,9.393939,0.757576,2.575758,1.818182,2.545455,1.621212,3.848485,5.469697,2.969697,0.939394,0.560606,1.803030,3.681818,12.030303,-379.0,0.257576,1517981.0,1606.424242,0.0,0.969697,0.000000,0.503226,0.294118,0.714286,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8588,2020,1.028571,2.057143,0.257143,0.857143,0.428571,0.514286,0.514286,1.142857,1.657143,0.371429,0.342857,0.114286,0.342857,1.085714,2.742857,-35.0,0.400000,940530.0,484.200000,0.0,0.142857,0.000000,0.500000,0.300000,0.833333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
8589,2021,1.176471,2.000000,0.294118,0.558824,0.764706,1.029412,0.617647,0.852941,1.470588,0.500000,0.117647,0.176471,0.323529,1.264706,3.411765,54.0,0.323529,1517981.0,506.352941,0.0,0.000000,0.000000,0.588235,0.526316,0.742857,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
8590,2020,1.961538,5.153846,1.243590,3.487179,1.243590,1.435897,0.371795,1.756410,2.128205,3.576923,1.230769,0.243590,1.192308,2.243590,6.410256,47.0,0.628205,3350400.0,1341.000000,0.0,0.000000,0.358974,0.380597,0.356618,0.866071,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8591,2021,1.666667,4.727273,0.909091,3.136364,1.000000,1.287879,0.348485,1.590909,1.939394,3.469697,1.030303,0.363636,1.060606,1.984848,5.242424,-239.0,0.560606,3200000.0,1160.015152,0.0,0.000000,0.075758,0.352564,0.289855,0.776471,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### Handle `SEASON_START` data

For `SEASON_START` data, we wouldn't want to use the exact year numbers, since we wouldn't want the first 2000 years to affect the normalization. Instead, we calculate the years passed since the first year in the dataset.

In [24]:
first_season = df['SEASON_START'].min()
first_season

2003

In [25]:
# Normalize SEASON_START by calculating years since first year in the dataset
df['YEARS_SINCE_2003'] = df['SEASON_START'].apply(lambda x: x - first_season)
df = df.drop(columns=['SEASON_START'])
df

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G,Atlanta Hawks,Boston Celtics,Brooklyn Nets,Charlotte Hornets,Chicago Bulls,Cleveland Cavaliers,Dallas Mavericks,Denver Nuggets,Detroit Pistons,Golden State Warriors,Houston Rockets,Indiana Pacers,Los Angeles Clippers,Los Angeles Lakers,Memphis Grizzlies,Miami Heat,Milwaukee Bucks,Minnesota Timberwolves,New Orleans Pelicans,New York Knicks,Oklahoma City Thunder,Orlando Magic,Philadelphia 76ers,Phoenix Suns,Portland Trail Blazers,Sacramento Kings,San Antonio Spurs,Toronto Raptors,Utah Jazz,Washington Wizards,YEARS_SINCE_2003
0,4.0,10.0,0.400,3.0,8.0,0.375,4.0,4.0,1.000,0.0,8.0,8.0,5.0,3.0,1.0,1.0,1.0,15.0,5.0,1,10245480,2182,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,18
1,9.0,19.0,0.474,4.0,11.0,0.364,3.0,3.0,1.000,0.0,3.0,3.0,5.0,1.0,0.0,0.0,3.0,25.0,-3.0,0,10245480,2067,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,18
2,7.0,15.0,0.467,2.0,8.0,0.250,0.0,0.0,0.000,0.0,1.0,1.0,3.0,2.0,1.0,4.0,2.0,16.0,7.0,1,10245480,1529,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,18
3,7.0,13.0,0.538,1.0,5.0,0.200,2.0,2.0,1.000,2.0,2.0,4.0,4.0,4.0,0.0,4.0,5.0,17.0,7.0,1,10245480,1942,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,18
4,5.0,13.0,0.385,1.0,6.0,0.167,4.0,6.0,0.667,1.0,2.0,3.0,5.0,1.0,1.0,2.0,3.0,15.0,-21.0,0,10245480,2266,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492307,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,-7.0,1,85683,189,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14
492308,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,-10.0,0,5503462,510,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,14
492309,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,-1.0,0,5503462,709,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,14
492310,2.0,3.0,0.667,0.0,0.0,0.000,1.0,2.0,0.500,1.0,9.0,10.0,0.0,0.0,2.0,2.0,3.0,5.0,-12.0,0,84546,1255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,13
492311,1.0,1.0,1.000,0.0,0.0,0.000,2.0,2.0,1.000,1.0,1.0,2.0,0.0,1.0,0.0,0.0,2.0,4.0,10.0,0,264010,474,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,6

In [26]:
avg_df['YEARS_SINCE_2003'] = avg_df['SEASON_START'].apply(lambda x: x - first_season)
avg_df = avg_df.drop(columns=['SEASON_START'])
avg_df

,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,WON_GAME,INFLATION_ADJ_SALARY,SECS_PLAYED,C,F,G,FG_PCT,FG3_PCT,FT_PCT,Atlanta Hawks,Boston Celtics,Brooklyn Nets,Charlotte Hornets,Chicago Bulls,Cleveland Cavaliers,Dallas Mavericks,Denver Nuggets,Detroit Pistons,Golden State Warriors,Houston Rockets,Indiana Pacers,Los Angeles Clippers,Los Angeles Lakers,Memphis Grizzlies,Miami Heat,Milwaukee Bucks,Minnesota Timberwolves,New Orleans Pelicans,New York Knicks,Oklahoma City Thunder,Orlando Magic,Philadelphia 76ers,Phoenix Suns,Portland Trail Blazers,Sacramento Kings,San Antonio Spurs,Toronto Raptors,Utah Jazz,Washington Wizards,YEARS_SINCE_2003
0,1.440000,3.840000,0.860000,2.440000,0.280000,0.320000,0.200000,1.280000,1.480000,0.520000,0.320000,0.100000,0.580000,0.860000,4.020000,-15.0,0.440000,3697550.0,846.440000,0.0,0.000000,0.000000,0.375000,0.352459,0.875000,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1.602740,3.794521,0.849315,2.013699,0.698630,0.863014,0.219178,0.986301,1.205479,0.739726,0.452055,0.027397,0.520548,0.958904,4.753425,33.0,0.534247,3938661.0,742.356164,0.0,0.000000,0.150685,0.422383,0.421769,0.809524,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0.771429,1.914286,0.314286,1.085714,0.114286,0.200000,0.142857,0.657143,0.800000,0.400000,0.171429,0.057143,0.314286,0.600000,1.971429,11.0,0.457143,4190683.0,439.200000,0.0,0.000000,0.028571,0.402985,0.289474,0.571429,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
3,0.833333,2.166667,0.583333,1.500000,0.166667,0.166667,0.166667,0.583333,0.750000,0.333333,0.000000,0.083333,0.416667,0.500000,2.416667,-2.0,0.833333,1577882.0,378.750000,0.0,0.000000,0.000000,0.384615,0.388889,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3
4,0.705882,1.941176,0.647059,1.529412,0.235294,0.235294,0.058824,0.647059,0.705882,0.588235,0.000000,0.058824,0.352941,0.705882,2.294118,-33.0,0.941176,1590374.0,403.294118,0.0,0.000000,0.000000,0.363636,0.423077,1.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8587,4.727273,9.393939,0.757576,2.575758,1.818182,2.545455,1.621212,3.848485,5.469697,2.969697,0.939394,0.560606,1.803030,3.681818,12.030303,-379.0,0.257576,1517981.0,1606.424242,0.0,0.969697,0.000000,0.503226,0.294118,0.714286,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18
8588,1.028571,2.057143,0.257143,0.857143,0.428571,0.514286,0.514286,1.142857,1.657143,0.371429,0.342857,0.114286,0.342857,1.085714,2.742857,-35.0,0.400000,940530.0,484.200000,0.0,0.142857,0.000000,0.500000,0.300000,0.833333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,17
8589,1.176471,2.000000,0.294118,0.558824,0.764706,1.029412,0.617647,0.852941,1.470588,0.500000,0.117647,0.176471,0.323529,1.264706,3.411765,54.0,0.323529,1517981.0,506.352941,0.0,0.000000,0.000000,0.588235,0.526316,0.742857,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,18
8590,1.961538,5.153846,1.243590,3.487179,1.243590,1.435897,0.371795,1.756410,2.128205,3.576923,1.230769,0.243590,1.192308,2.243590,6.410256,47.0,0.628205,3350400.0,1341.000000,0.0,0.000000,0.358974,0.380597,0.356618,0.866071,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17
8591,1.666667,4.727273,0.909091,3.136364,1.000000,1.287879,0.348485,1.590909,1.939394,3.469697,1.030303,0.363636,1.060606,1.984848,5.242424,-239.0,0.560606,3200000.0,1160.015152,0.0,0.000000,0.075758,0.352564,0.289855,0.776471,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18

Given that `INFLATION_ADJ_SALARY` is the target variable, we will place it at the end of the dataframe:

In [27]:
cols = df.columns.tolist()
cols.remove('INFLATION_ADJ_SALARY')
cols.append('INFLATION_ADJ_SALARY')
df = df[cols]
avg_df = avg_df[cols]

### Save dataframes

In [28]:
df.to_csv('../data/preprocessed/stats_salaries.csv', index=False)
avg_df.to_csv('../data/preprocessed/stats_salaries_avg.csv', index=False)

### Potential ideas for improving the data quality
1) Add more information like position of all players, salary cap of each team
2) Use the original salary (not inflation-adjusted) and let # years variable account for the inflation
3) Calculate additional features (e.g., "weight" of salary based on team salary cap, total league salary)